server:
  port: 8301
spring:
  application:
    name: config
  profiles:
    active: git #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
  cloud:
    config:
      server:
        git:
          uri: https://github.com/caodmeng/code # 配置git仓库的地址（最后不需要带/，否则会出现：No custom http config found for URL: XXX）
          search-paths: code/eureka/configFile                             # git仓库地址下的相对搜索地址（可用使用通配符），可以配置多个，用,分割。可以{application}实现按应用查配置
          username:                                             # git仓库的账号（公开仓库无需账号信息）
          password:                                             # git仓库的密码（公开仓库无需账号信息）
          default-label: master                             #git默认分支
#访问  localhost:8301/cons/default
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address} # 服务治理地址显示为ip地址
    instanceId: ${spring.cloud.client.ip-address}:${server.port} #服务治理地址显示为ip地址 默认：服务器宿主机名称+服务名称+端口号
  client:
    register-with-eureka: true #当springboot启动完成后是否将该服务注册到服务治理服务器上 false不注册
    #如果一个服务实例单纯地仅作为服务消费者并不对外提供服务那么register-with-eureka可以设置为false
    fetch-registry: true #应用启动后不需要从服务治理服务器中同步已注册的服务注册列表数据到本地，
    #如果一个服务实例单纯地仅作为服务提供者并不消费其他服务那么fetch-registry可以设置为false
    serviceUrl: #eureka服务器地址
      defaultZone: http://localhost:8888/eureka/


