server:
  port: 8301
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/caodmeng/code/tree/master/code/eureka/configFile
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address} # 服务治理地址显示为ip地址
    instanceId: ${spring.cloud.client.ip-address}:${server.port} #服务治理地址显示为ip地址 默认：服务器宿主机名称+服务名称+端口号
  client:
    register-with-eureka: true #当springboot启动完成后是否将该服务注册到服务治理服务器上 false不注册
    #如果一个服务实例单纯地仅作为服务消费者并不对外提供服务那么register-with-eureka可以设置为false
    fetch-registry: true #应用启动后不需要从服务治理服务器中同步已注册的服务注册列表数据到本地，
    #如果一个服务实例单纯地仅作为服务提供者并不消费其他服务那么fetch-registry可以设置为false
    serviceUrl: #eureka服务器地址
      defaultZone: http://localhost:8888/eureka/


