server:
  port: 8080
spring:
  application:
    name: zuul
eureka:
  client:
    service-url: #eureka服务器地址
        defaultZone: http://localhost:8888/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 28000
  ConnectTimeout: 28000
#自定义网关路由配置
zuul:
  host:
    socket-timeout-millis: 28000
    connect-timeout-millis: 28000
  routes:
    cons:
      path: /cons/**
      serviceId: cons
      sensitiveHeaders: X-ABC


