# Use a larger VM as we run a lot of services
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty

language: java

# Spark doesn't support Java 9+, yet https://issues.apache.org/jira/browse/SPARK-24421
jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
  - $HOME/.m2

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  # Required for Elasticsearch 5 (See https://github.com/docker-library/docs/tree/master/elasticsearch#host-setup)
  - sudo sysctl -w vm.max_map_count=262144

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -DskipTests=true -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "eXQ9PAKzb0y10K400Kh3NRjil9yJx99v0Iefvgj7VkEVixc5CgF1QjrPD9CAQuEnXsLXkrcAulU4K0UtyR3TV03auN4Qmo0NRvWMRAP71rWJ2KMLrHgOkSOzY3rS2Cec9EFE6sBCWJK/Rp6jg/AtJf3sBSBC+NlXfNZ09HAOl3G2KEihK6ZEeix80RlRk2sSvd53ZkdZxk7qiNLO7s2RvCg7yhmi17+7wIMsQERMlvJQZ+4KAIaTUuDgeHX78+fZDB4+Xao9iMGZvn148qZ9xM2Eax8w71xDlzHwrGVuSRs8v0iv1dnR5uFnaQHgHT2eusjUmpalT6Fqhz4lGjA19WhD/3HdS0iSS5KjI71Go0A3j6tVNcSFHYTq17S0hDcaVuKCScktLul1ONQ05AYB0LQPEUr1TYl5nw2MUqL0trNLQrRT97dqv2Q23qlbL2MOnpABuEOHmtH5Hy1GltMt2kEmrLU/QeZ8OMq6OPH2CnNKE7mQQsOnc4HZ+jGqPQKWSWI1H9IVIKaRw7ol9bQXxdeDiJwWKbPs9mZDLPDM0kl9U3ljj1T2k7XY/S1ALh3Wj3QS9kcpjYQVpF/k5XqnI4qBIhTv/pttwqoHlH1NvWvnlkCNZqLjZjWYQBBieB85nmDcuXHHuFSNusDboq4opTJty0rSPztHOdEPnMCM4uM="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx
    - secure: "KQllvoBzINEvWL9M/xYrvwyjWGCEGwy6u4ReSgutuN064FBOgGXoXVIodOCurK03vABcjXZvP7SzzqcmJ8udEst5HtGakMo1p13N80AM1fk2XZI1q11r0D6PvVldTsHJ41x9hAUag0di+RiitHpMO4nZvA3JOpDxuYZ68wBX8SzNKq6ahYSN/xlKu08G05yA1bIazRISvn6kTcM8lx6YZjqRaIztqfNbF+Kwf6GvlmtwnA9DsTO4aBQnzuBnTht5aicth7OGPUfo2YsqSyFWFApOW4Wpx4bJWn2o3p61NnA+ocwKD5FFsvjUhgB3asle5mdEXeiSyt+ee5tlqQdmQ/9BRrnpL37vgWrlfv3pjeXXAJklmdul/jmcinFzBduX0/QRDHo2XCJgA2R0FPSbCOhCbXG65bAKJV1HbpWOyOiccyTds0WFDmqdT53SBHTkU+/AV4aZZF1Uw3U/jJ/ssLAFIb1lpeXvR42/1tXmAmog0pi97xFrrwb3fu3WUDmRvxUGt0c/qmsZM+WOBbnE/sSElZlCG7AvlESSKjVgCsTT3Hq6e8xz1p/0fLSGyDiaM+eIyva6xeYR7eqyBhLQrmD/+JR3SxNkmHsWb33EpDGRptMtmyvzTqjC2jT3/WACqojqNxMVlg/nLnqSR3D7nY49U6e97LN6X9ztkppAWjE="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
    - secure: "ROcFc1+W0xf0DLZAGgHycYkhB2jmFm3xb33aPFan/GXojv1FCr8SzJMAWbg6d2KJSU/NJ9ioJanM79VzRrZg7jKMr0/B1P1KPF7hakqZ1qRMmTW0DE1XG0WKZm10DzoJqTf6pwNMowohx5hz79vODXdw+eFTyhaa24o0YOy0xOkjpEBjjioGt6/7q+r8L4eHdExKX26bcXT2uKODVxBxq0vIJXTP+EWD2k1JEd78D6iHYgmTuNzK7ijolJwkSqHkDPHfl4gwqUaqXa5+1bo2DXfyXS7jnwCASDTtc/nzXRA1hBslGxoUtZpTgLtQvjGse5WOah9SKN5mwsCYVUgVKho2YmVhWxXocBIcebTE7N64+d5V2qJV+37ok3w6yf9p7dS+/fmYdR0R8YzlOc4E/1o6Gkd9i17PkKAWhApXejoQyKMwve7KtJDrs0F+UG5cDoZ274j0Osm7aF8zdxReyVD/eyGhHdUHQrkpIlYXpIU3OdBBX6OM0HfiOqUf9WwSs/AL1QTTISOK6r1ooJFM+cxNDaxXOnq3meBCFoMGT47qVckEk7/fN2GEWvNLxMa70Lw5kQBSbIVt978+yGpUL2lMPsEnf2f0MKcFRw1eoWEWi6UgF5hROxwTwQCA/SxQGhV6HsQlyLflXNJjlswbvDD6awIYqJhfi/PfHgUTl58="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "T4iU1w/QC65qzeLMAZRmDqWwLITghtJaUWUvDFyPbHGSeIHEBkxb25wDobK4F7N/e/xWXxyIFb/1Cu0tKvT2OVY98bwrlUXBVskPGQk7V5T/ExhEP5i1FMerbG04FSuBmH0i6/5BX0CcIoeFuQAH5OImvX81yEnBtxxdkYrwjTjyrD0XEZHXs3ychFhjTI1LpyUIb4v12HdF/BXG921OJJgxoaf6976Z683RtwZBllbmAVtbfJ2TMORbPuWbG1zSNNwcEkvrSsitucsZ5azd0QXrHkHI3Ata4rRdus6/pxMRE2SHe8zmZ6vMstD65LngqkD4Bg4dNvcGVK6a0rzniARBXDUXjP0G0lQjK+MPDIKJafaPbOjuAdVyJdZdoTWm75CYSRc+DNHDoV7xXf9L2tGZLz5Ke0ZCenqkV4GGghaolcaeBBe07DO3iUnAwzlsJV5JD1tsreSuUhnzWKXTf9YvEpp7FwCcQG03VliaZxe94ecSUCUv2qWRBqjxlf61vm0eLNWe8urILjwrQlK0B8TU3dPilGq3SlYnT3rmlkMcXDfR+81eA6c5cSNmw0JW7fLU19N0Nm3b6NJliQ0ER1PgEAEP6sFgH0lNZuY6ZuWzRUQcU8U5TqKs5BbZDun2AylJrcxHaxfMeVzV3deSpnPJZTxVc6SM/pvO7hIV6dc="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "ro21SCB8PDwwizbxBHxm/G2m8VmhuYDyQsybmOekf+zrD23QmoCTDuL2YpFrBPGb3Doudd/cL839SXIMYWBCwqypnSVWeqJ9ysQ9hYceBQpfdriHp+ECCs+roghty+NiZpCUwzYNBJT/MdPxSbn6w03UWmY5CsrBvOm3c0/ylIJltXQ35lrqkXGfE729HJOrWdlj3dIu4pcVgDaBwKx2CTb7xBvv37O783xT6IpVRN071E697gii/PFtRujkBjBAYoUQbZ76LgncanvA06VmeXGRwVdgXQygJke+yngyVPEjpKVqewgtsDnqYVKuVK6T0OZLi0kk3jdV9R6g+irMATsi2NEhZ+gaoIGrnRSLaPQSc9r8czRBMw0KXcNQDxQTVtT8yp1z3lK0ZjkIay+IiRidgo7KubBQx6HVK10kavlCS3ZWVzGB1IKfVHQwBXvRtkJui6smsCmiPGCks4fyV6108p424Vft7objz3CTgc0lgqG+q1D5TXuFwSbAXhVgyn+Nfd3gz+/TjrFnBxQbAfP/J9h2lq9gsr3hkm4DKPww9On0fNllH/xyWJ03HtL79W1QdlGHxHdUWFrFxGRnwF0lXY5xu3/1fRNt9q80P+Om9cYGL5Yia62TGYP5QMIIs7YkWRv+PKBJLF0YG11CuHK34JVb3LbkU+j+a77dauM="

    # To trigger Docker image publication, we need the Trigger Url from https://cloud.docker.com/u/openzipkin/repository/docker/openzipkin/zipkin/builds/edit
    # However, this is too big for travis encrypt. Instead, we decompose it into
    # two variables: https://cloud.docker.com/api/build/v1/source/${DOCKER_HUB_SERVICE_UUID}/trigger/${DOCKER_HUB_TRIGGER_UUID}/call/
    # Ex. travis encrypt DOCKER_HUB_SERVICE_UUID=https://cloud.docker.com/api/build/v1/source/XXX/trigger/...
    - secure: "aBolDCWqBcIlu2waK1/yGU8XpQp9KtDJGmBZ9YCUk6tJL3pG/QEYBB+HELxAV3P1L+JpI8z8pR2EebMbDedy/X2nQxZFOCe+LehKvXn6VAbUiGpcJbzS9DwQ7gJ5sN9ZZ1r7Cs2d5ij/SMlEv4bLVhgJMNf0GZZmGadp+X0vichBIqSfSY0f54yzwVCGt9JcwkMtlWOqjcZxQRcHYQ2+2QuEgItXIHqf8ArnmK/lohz93fqT+MLqcxp6pnOgZcPovuYjUjfF+cezCZk2KHc0NoXiZLy5f9P2RD6PU91L/5OcjCSyzb/M9axJ5x984QoX0Rm7W4okvwg/IteaTZCDiwt/6c1hQNANbHj9/bblHetuwHSxzsBzIyGFSLsVqsytDWF9ib0wAAvh3/0A8mBb8gcTr6ghvNL2+GLsS+cmLm/qqbcL9/pHd219pxo4GDLNSOwm9ScdShY1sxoMZ3/E3olp7Dhbr8iORwUBkjO2DiZNHxxgSxLWVitfjjJrRwvX/ffm8p/IySBovZK32325uTza1yBvLn7/4oljGEei+14RJW6zrcTGb/nPEJfz9UGe0fzsCazLD+YXfPXOgWqzvqDTUTgxTcCX9x7jRaTl1dqAHIC3jRostaDBAVde9sWSr0z9dUE5c1+SkHLgZLkqRQEE+2TJsJzvtVwE/hBInK8="
    # Ex. travis encrypt DOCKER_HUB_TRIGGER_UUID=https://cloud.docker.com/api/build/v1/source/.../trigger/XXX
    - secure: "mesKjEWe5SNicY+faNvlE4rq1MNcuN5JdOiXFC2ec07eouS3Iq9GTh7Kh0DkhyR1ghRyFo1VZ09oCMSVk9CUU3IX70zffEh47HYqpIlGKeL18+qk+IC9vtKSllfQvf12HyB/JywW8/QAaUajopbslS9PEF7OHqowQvpWwbh0AID2JJwKbjRLIv+d4/DJU3Qhq+P76xFvLF+59Nj3O/5ainKmwFwaWyBnNGVRWP4WiO0Rd8VN+c7LSI7NEVRFnw4itKfkQGhpSObX6pEXbfhtOTYvDQZ33krfAAiOBYwPd0GMDDYnEoTzUmN4SGejBJyhI8M+wOBfb9EZicrMTZwBfgEbAumtAkdfh7wGiZe3lH4lJcUa+D2tb8qpX2QtgoffhjSjR4g9JkQvgOl1oihWlenv0/SmLEqlrIJDulq9dYp/DkWVF3ALmkku/QV/pvy5vwZ7xg7LHU4b97tMKz3yuQgz2Xak9vRxONqAF77yN56+TYxy1s1HKwc5EJ1Vj6q9QhVPYGlekQBhIo75srIo/z7WgeDIMsS7/wFvVFAGyo5E0AnL1DiOPtPh2EBKFQokZZGHs072dT2ah//MJVcakwk5Gt69925yX9tdEp0+kDwZyAy9bzjUDPvluJqLMJFUS9KamFFFyomFw/Q+6z12+sG4PoG3qffIyo/n7pUdllQ="
